JuzDzis/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
]

pages/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'pages'
urlpatterns = [
    path('', views.index_view, name='index_view'),
    path('onas/', views.onas_view, name='onas_view'),
    path('aktualnosci/', views.actual_view, name='actual_view'),
    path('kontakt/', views.kontakt_view, name='kontakt_view'),
    path('zajecia/', views.zajecia_view, name='zajecia_view'),
    path('register/', views.register_view, name='register_view'),
    path('login/', views.login_view, name='login_view'),
    path('profile/', views.profile_view, name='profile_view'),
    path('logout/', views.logout_view, name='logout_view'),
]

pages/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User
import random

# Create your models here.


class Messages(models.Model):
    title = models.CharField(max_length=30, blank=True, null=True, default='')
    desc = models.TextField(max_length=20000, blank=True, null=True, default='')
    user_email = models.CharField(max_length=50, blank=True, null=True)
    sender = models.CharField(max_length=30, blank=True, null=True)
    pub_date = models.DateTimeField('Data Wysłania', blank=True, null=True)
    def __str__(self):
       return str(self.title)
class Lessons(models.Model):
    title = models.CharField(max_length=30, blank=True, null=True, default='')
    desc = models.TextField(max_length=2500, blank=True, null=True, default='')
    link = models.CharField(max_length=300, blank=True, null=True, default='')
    pub_date = models.DateTimeField('Data publikacji')
    image = models.FileField(upload_to='static/', blank=True, null=True)
    def __str__(self):
        return str(''+ self.title)

class Texts(models.Model):
    title = models.CharField(max_length=30, blank=True, null=True, default='Tytuł sekcji',)
    desc = models.TextField(max_length=15000, blank=True, null=True, default='Opis')
    pub_date = models.DateTimeField('Data publikacji')
    link = models.CharField(max_length=2000, blank=True, null=True, default='')
    link_name = models.CharField(max_length=2000, blank=True, null=True, default='')
    image = models.FileField(upload_to='static/', blank=True, null=True)
    def __str__(self):
       return str(self.title)

pages/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class CreatUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'email', 'password2', 'first_name']

pages/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import CreatUserForm
from .models import Texts, Messages, Lessons
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import HttpResponse
from django.utils import timezone
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import time

def index_view(request):
    return render(request, 'pages/index.html')

def onas_view(request):
    return render(request, 'pages/onas.html')

def actual_view(request):
    listoftexts = Texts.objects.order_by('-pub_date')
    context = {
        'listoftexts': listoftexts,
    }
    return render(request, 'pages/aktualnosci.html', context)

def kontakt_view(request):
    info_message = None
    context = {
    }
    if request.method == 'POST':
        if request.user.is_authenticated == True:
            user = User.objects.get(username=request.user.username)
            message = Messages()
            message.title = request.POST.get('title')
            message.user_email = request.POST.get('email')
            message.desc = request.POST.get('desc')
            message.pub_date = timezone.now()
            message.sender = user.username
            if message.title != "" and message.user_email != "" and message.desc != "":
                message.save()
                info_message = 'Wiadomość została wysłana.'
            else:
                info_message = 'Jedno lub więcej z powyższych pól nie jest wypełnione.'
        else:
            info_message = 'Błąd, nie jesteś zalogowany(a)!'
    context = {
        'info_message': info_message,
    }
    return render(request, 'pages/kontakt.html', context)

@login_required(login_url='../login')
def zajecia_view(request):
    listofLessons = Lessons.objects.order_by('-pub_date')
    context = {
        "listofLessons":listofLessons
    }
    return render(request, 'pages/zajecia.html', context)
def register_view(request):
    form = CreatUserForm()
    if request.method == 'POST':
        form = CreatUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(request, username=username, password=password)
            #return redirect('../login/')

    context = {
        'form': form,
    }
    if request.user.is_authenticated == True:
        allog = 'Jeteś już zalogowany!'
        context = {
            'form':form,
            'allog':allog
        }
    return render(request, 'pages/register.html', context)
def login_view(request):
    if request.user.is_authenticated == False:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('../')
            else:
                messages.info(request, 'Hasło Bądź login nie jest poprawne! ')
        return render(request, 'pages/login.html', context=None)
    else:
        return redirect('../register/')

@login_required(login_url='../../login')
def profile_view(request):
    username = None
    first_name = None
    email = None
    ps_ch = False
    if request.user.is_authenticated == True:
        username = request.user.username
        first_name = request.user.first_name
        email = request.user.email
        sucess = ''
    context = {
        'username': username,
        'first_name': first_name,
        'email': email,
        'sucess': sucess,
    }
    if request.method == 'POST':
        user = User.objects.get(username=username)
        if request.POST.get('first_name') != '':
            user.first_name = request.POST.get('first_name')
            sucess += 'Imię, '
        if request.POST.get('password') != '':
            user.set_password(request.POST.get('password'))
            sucess += 'Hasło, '
            ps_ch = True
        if request.POST.get('email') != '':
            user.email = request.POST.get('email')
            sucess += 'E-mail '
        if sucess != '':
            sucess += 'Zmiany zostały zapisane'
        user.save()
        context = {
            'username': username,
            'first_name': first_name,
            'email': email,
            'sucess': sucess,
        }
    if ps_ch == True:
        return redirect('../../login')
    return render(request, 'pages/profile.html', context)
def logout_view(request):
    logout(request)
    return redirect('../login')

pages/templates/pages/aktualnosci.html
{% extends 'base.html' %}


{% block main %}

{% for text in listoftexts %}

<section id="section-{{obja.id}}" class="secc">
    {% if text.image %}
        <img class='actimg' src="../..{{ text.image.url }}">
    {% endif %}

    <h1>{{ text.title }}</h1>
    <p>{{ text.desc }}</p>
	<br>

    {% if text.link_name %}
        <p><a href="{{  text.link }}">{{ text.link_name }}</a><p>
    {% endif %}
</section>

{% endfor %}

{% endblock %}

pages/templates/pages/index.html
{% extends 'base.html' %}


{% block main %}

<section id="section-2" class="secc">
      <h1>Witaj na JużDziś!</h1>
      <p>Witaj w przyszłości! Jest tu! trzymasz ją w rękach.</p>
  </section>
  <section id="section-3" class="secc">
      <h1>Dlaczego?</h1>
      <p>Na samym początku musimy odpowiedzieć na najtrudniejsze pytanie, dlaczego w małej grupie stworzyliśmy Już Dziś? Odpowiedź wbrew pozorom jest prosta! Sami jesteśmy uczniami i Pamiętamy jak bardzo taka platforma mogłaby się nam przydać. Tym bardziej mając na uwadze to, że niektórzy z nas Już Dziś! sami próbują swoich sił na rynku pracy. Myślimy zatem, że Wy też szukacie miejsc, gdzie będziecie mogli profesjonalnie poszerzać swoją wiedzę. Już Dziś! staje się to prostsze!</p>
  </section>
  <section id="section-4" class="secc">
      <h1>Cele projektu</h1>
      <p>Naszym głównym celem jest pomaganie Wam w wykorzystaniu swojego potencjału. Będzie to możliwe dzięki wykładom prowadzonym przez ludzi, a organizowanym przez naszą witrynę którzy sami osiągneli sukces w danej branży i chcą się nim podzielić z Wami i dać Wam przepis na sukces. Już Dziś! masz szansę wziąć przyszłość w swoje ręcę!</p>
  </section>
  <section id="section-5" class="secc">
      <h1>O projekcie</h1>
      <p>Już Dziś! to projekt społeczny od uczniów - dla uczniów. W ramach Innowacyjnej platformy Zwolnieni z Teorii powstała ta platforma streamingowa na której Już Dziś! możesz znajeźć kursy idealnie dopasowane do ciebie. Już Dziś! razem z nami naucz się czegoś nowego!</p>
  </section>
{% endblock %}

pages/templates/pages/kontakt.html
{% extends 'base.html' %}
{% load static %}
{% block main %}

<form class='form_register' method="POST" style='margin-top:100px;'>
    {% csrf_token %}
    <p>Kontakt z adminiatracją Już Dziś</p>

    <input class="uname2" type='text' name="title" maxlength="30" minlength="2" placeholder=" Tytuł">

    <textarea class="uname2" type="text" name="desc" maxlength="20000" minlength="10" rows="4" cols="50" style='width:90%;' placeholder="Opis"></textarea>

    <input class="uname2" type='email' name="email" maxlength="40" minlength="2" placeholder=" Email do kontaktu" value="{% if def_email  %} {{ def_email }} {% endif %}">
    <hr class='div-form'>
    <input class="button1" type="submit" name="Send">
    {% if info_message %}
        <div id='info'>
            <p>(!) Info</p>
            <p>{{ info_message }}</p>
        </div>
    {% endif %}
</form>

<div id='social_contact'>
    <table class="konttable" >
            <tr>
                <th><img class="log1" src='{% static "flogo.png" %}' style='height: 50px;'></th>
                <th><a href="https://www.facebook.com/Ju%C5%BC-dzi%C5%9B-projekt-spo%C5%82eczny-102323845029962" style='text-decoration: none; color: white'>Facebook</a></th>
            </tr>
            <tr>
                <th><img id="log2" src='{% static "inslogo.png"%}' style='height: 50px;'></th>
                <th><a href="https://www.instagram.com/juzdzis/" style='text-decoration: none; color: white'>Instagram</a></th>
            </tr>
            <tr style='color:white;'>
                <th><p class="log1" style='font-size: 50px; margin:0;'>@</p></th>
                <th><a>administracja_projektu@juz-dzis.pl</a></th>
            </tr>
        </table>
</div>

{% endblock %}

pages/templates/pages/login.html
{% extends 'base.html' %}

{% block main %}

<form class='form_register' method="POST" action="">
    {% csrf_token %}
    <p>Zaloguj</p>
    <input type="text" name="username" placeholder=' Login:'>
    <br>
    <input type="password" name="password" placeholder=" Hasło:">
    <br>
    <input class="button1" type="submit" name="Create User">
    <br>
    {% for message in messages %}
        <p id="info"> {{ message }} </p>
        <br>
    {% endfor %}
    <a class="login1" href = '{% url "pages:register_view" %}'>Nie masz konta? Załóż już teraz!</a>
</form>

{% endblock %}

pages/templates/pages/onas.html
{% extends 'base.html' %}


{% block main %}
            <section id="section-1" class="secc">
                <h1>Witaj!</h1>
                <p>Na zakładce O nas, w której  możesz bliżej Nas poznać!</p>
            </section>
            <section id="section-2" class="secc">
                <h1>Jak to się zaczęło</h1>
                <p>Witajcie!	Dziś chcielibyśmy pokazać Wam jak, gdzie i skąd pojawiło się "JużDziś!". Jak wiadomo aby narodził się pomysł, musi zaistnieć potrzeba jego stworzenia. W naszym przypadku była ona prosta - Znaleźliśmy niszę która nie jest zaspokojona.</p>
                    <p>Otóż na naszej, rodzinnej scenie e-edukacyjnej brakuje prostej, intuicyjnej w użytku i szeroko dostępnej platformy z równie intuicyjnymi i stworzonymi w dobry sposób kursami, wykładami, czy też prelekcjami.</p>
	             <p>Z tym przyświecającym Nam pomysłem, przystąpiliśmy do rozmowy na temat tego, jakie istnieją sposoby na jego rozwiązanie.Wtem doszła do nas myśl, iż idea rozwiązania naszego problemu może nadejść równie łatwo, jak jego powstanie.</p>
                 <p>Zdawaliśmy sobie sprawę jednak, że nie wystarczy mieć tylko prostego rozwiązania.Cały plan okazywał się coraz bardziej skomplikowany im bardziej się w niego zagłębialiśmy. Jak to często się mówi - „Apetyt rośnie w miarę jedzenia.”Sam projekt wymagał od nas bardzo dużego zaangażowania i ciężkiej pracy. Dniami siedzieliśmy uzgadniając kwestie odnoszące się do kolejnych i kolejnych spraw.. natomiast wieczorami następował czas na ich wykonanie aby uzgadniać następne kwestie po szkole dnia kolejnego.</p>
	             <p>Tak też po zdaniu sobie sprawy z ogromu prac, kilkukrotnie mieliśmy chwile zwątpienia. Bardzo mało brakowało, aby JużDziś! Nigdy nie ujrzało, cóż, swojego dnia.Jednak, na całe tak Nasze, jak i Wasze szczęście rozłam w naszym zespole nie miał miejsca.	Tak więc teraz krok po kroku przejdziemy przez wszystkie etapy, przez które musieliśmy przejść aby JużDziś! powstało.</p>
                 <p>Na samym początku potrzebowaliśmy pomocy w tworzeniu JużDziś! W szkole dowiedzieliśmy się o Zwolnieni z Teorii, z pomocą których tworzony jest ten projekt.Działo się, musieliśmy wymienić cały zespół, zwinąć biuro i pracować zdalnie, a nawet 		zrezygnować na chwilę z JużDziś! i zaangażować się w inne projekty.
	                Jako kilku-osobowy zespół z zerowym doświadczeniem w biznesie, marketingu czy sprzedaży byliśmy skazani na.., cóż, porażkę.Wtedy na szczęście nie byliśmy tego świadomi :),<br>
                    Nie mając żadnego doświadczenia i inwestując prawie zerowe kwoty (nie licząc tysięcy godzin naszego prywatnego czasu) udało nam się doprowadzić do uruchomienia portalu.</p>
	             <p>W okolicach października 2020 roku zaczęliśmy rozglądać się za inwestorem. Mieliśmy wrażenie, że pieniądze rozwiążą wszystkie nasze problemy i portal auto-magicznie (sic!) sam zacznie się rozwijać.
                    Po czasie zrozumieliśmy, że to nie pieniędzy nam brakowało tylko wiedzy i doświadczenia. Zamiast uczyć jak prowadzić biznes, jak wygląda nasz rynek, jakie problemy mają nasi klienci i jak chcemy je rozwiązać  skupiliśmy się na szukaniu finansowania co skutecznie odciągało naszą uwagę o sednie przedsiębiorczości.
                    Teraz wiemy, że pieniądze niewiele pomogą jeśli nie masz poukładanych podstawowych aspektów jak zespół, itd.</p>
            </section>
            <section id="section-3P" class="secc">
                <h1>Dawid</h1>
                <p>Dawid to współtwórca naszej platformy. Jest to bardzo odpowiedzialna osoba, zawsze wywiązuje się ze swoich zadań i chętnie zagłębia swoją wiedzę. Ma swoje pasje i spełnia się w nich. Ale też myśli o innych i potrafi poprawić humor każdemu.</p>
                <img id='photoD' src='../../../static/pDawid.jpg'>
            </section>
	        <section id="section-5P" class="secc">
		            <h1>Klaudia</h1>
		            <p>Klaudia jest to bardzo miła oraz bardzo uczynna dziewczyna która za wszelką cenę chce pomóc innym. Bardzo się stara aby wszystko wyszło w tym projekcie najlepiej jak się tylko da. Poświęca cały swój wolny czas projektowi oraz myśli co może zrobić aby było tylko lepiej.</p>
                <img id='photoK' src="../../../static/pKlaudia.jpg" alt="dqif">
            <section id="section-4P" class="secc">
          </section>
          <h1>Alosza</h1>
          <p>Alosza to główny deweloper naszej strony internetowej, jak i platformy do nauczania której właśnie używacie. To cierpliwy, chętnny do pomocy programista. Rozwija się w tym kierunku. Jest pełnym pasji i zaangażowania nastolatkiem który zarazi was chęcią nauki i poszerzania swojej wiedzy.</p>
          <img id='photoA' src='../../../static/pAlosza.jpg'>
          </section>
  {% endblock %}

pages/templates/pages/profile.html
{% extends 'base.html' %}

{% block main %}

<div class='profile'>
    <form class='form_register' method="POST" action="">
            {% csrf_token %}
            <h1>Ustawienia</h1>
            <hr class='div-form'>
            <a class="fields">Podaj nowe imię </a><input class="uname1" type='text' name="first_name" maxlength="16" minlength="2" placeholder=" {{ first_name }}">
            <br>
            <a class="fields">Podaj nowe hasło </a><input class="uname1" type="password" name="password" maxlength="500" minlength="6" placeholder=" ******">
            <br>
            <a class="fields">Podaj nowy e-mail </a><input class="uname1" type="email" name="email" maxlength="50" minlength="6" placeholder=" {{ email }}">
            <br>
            <hr class='div-form'>
            <a class="fields"></a>
            <input class="button1" type="submit" name="Create User">
            <br>
            {% if sucess %}
                {{ sucess }}
            {% endif %}
    </form>

    <div class='action'>
        <a id='logout' href="{% url 'pages:logout_view' %}">Wyloguj</a>
    </div>
</div>

{% endblock %}

pages/templates/pages/register.html
{% extends 'base.html' %}


{% block main  %}

<form class='form_register' method="POST" action="">
    {% csrf_token %}
    <p>Załóż konto na naszym portalu</p>
    {{ form.username }}
    <!hr class='div-form'>
    {{ form.first_name }}
    <hr class='div-form'>
    {{ form.email }}
    <hr class='div-form'>
    {{ form.password1 }}
    <hr class='div-form'>
    {{ form.password2 }}
    <hr class='div-form'>
    <input class="button1" type="submit" name="Create User" value="Zatwierdz" style=''>
    <br>
    <a class="login1" href = '{% url "pages:login_view" %}'>Już masz konto? Zaloguj!</a>
    {{ form.errors }}
</form>

<script type="text/javascript">
    document.getElementById("id_username").placeholder = " Login:";
    document.getElementById("id_first_name").placeholder = " Imię:";
    document.getElementById("id_email").placeholder = " Email:";
    document.getElementById("id_password1").placeholder = " Hasło:";
    document.getElementById("id_password2").placeholder = " Powtórz hasło:";

</script>

{% endblock %}

pages/templates/pages/zajecia.html
{% extends 'base.html' %}
{% load static %}
{% block main %}

<div id='seccontainer'>
    {% for lesson in listofLessons %}
    <div class="kwadrat">
        <img onclick="myFunction('{{ lesson.link }}')" src="../..{{ lesson.image.url }}">
        <div class="title"><p>{{ lesson.title }}</p></div>
        <p>{{ lesson.desc }}</p>
    </div>
    {% endfor %}
</div>

<script>
    function myFunction(arg1) {
        var div1 = document.getElementById("lessonWindow");
        var label = document.getElementById("videoLesson");
        if (div1.style.display === "none") {
            div1.style.display = "block";
            label.src = arg1;
        } else {
            div1.style.display = "none";
        }
    }
</script>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">
    <link rel="shortcut icon" href="{% static 'favicon.ico'%} " type='image/x-icon'>
    <title>Już Dziś</title>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-30X7D4V77S"></script>
	<script>
		  window.dataLayer = window.dataLayer || [];
  	function gtag(){dataLayer.push(arguments);}
 	 gtag('js', new Date());

	  gtag('config', 'G-30X7D4V77S');
	</script>
  </head>
  <body>
    <div id='navbar'>
      <a href="{% url 'pages:index_view' %}"><img src="{% static 'logo.png' %}" id='logo'></a>
      <ul>
        <li><a href="{% url 'pages:actual_view' %}">Aktualnosci</a></li>
        <li><a href="{% url 'pages:onas_view' %}">O nas</a></li>
        <li><a href="{% url 'pages:kontakt_view' %}">Kontakt</a></li>
        <li><a href="{% url 'pages:zajecia_view' %}">Zajęcia</a></li>
        <li><a href="{% url 'pages:profile_view' %}">Profil</a></li>
      </ul>
    </div>
    <div id='navphone'>
      <nav>
      <label for="touch"><span>Menu</span></label>
      <input type="checkbox" id="touch">
      <ul class="slide">
        <li style="padding-bottom:0;"><a href='{% url 'pages:index_view' %}'><img src="{% static 'logo.png' %}" style="height:50px;"></a></li>
        <li><a href="{% url 'pages:actual_view' %}">Aktualnosci</a></li>
        <li><a href="{% url 'pages:onas_view' %}">O nas</a></li>
        <li><a href="{% url 'pages:kontakt_view' %}">Kontakt</a></li>
        <li><a href="{% url 'pages:zajecia_view' %}">Zajęcia</a></li>
        <li><a href="{% url 'pages:profile_view' %}">Profil</a></li>
      </ul>
      </nav>
    </div>
    <div id='main'>
      {% block main %}

      {% endblock %}
    </div>
    <div id='foother'>
      <i>Strona stworzona w ramach konkursu "Zwolnieni z Teorii"</i>
    </div>
  </body>
  <div id="lessonWindow">
        <div class="close-container" onclick="myFunction('{{ lesson.link }}')">
            <div class="leftright"></div>
            <div class="rightleft"></div>
        </div>
        <iframe id="videoLesson" width="420" height="315" src="https://www.youtube.com/embed/gQkwzVnXyh4" frameborder="0">
        </iframe>
    </div>
</html>